---
- name: "Include default variables in {{ SITE_DEFAULTS }}"
  include_vars:
    file: "{{ SITE_DEFAULTS }}"

- name: Install {{ SITE_NAME }} image stream on OpenShift
  k8s:
    state: present
    name: "{{ SITE_NAME }}"
    host: "{{SITE_HOST}}"
    api_key: "{{SITE_TOKEN}}"
    namespace: "{{SITE_NAMESPACE}}"
    definition: "{{ lookup('template', '{{ SITE_SRC }}/openshift/SITE_IMAGE_STREAM_1.yml') }}"
    validate_certs: false
- name: Install {{ SITE_NAME }} secret on OpenShift
  k8s:
    state: present
    name: "{{ SITE_NAME }}-secret"
    host: "{{SITE_HOST}}"
    api_key: "{{SITE_TOKEN}}"
    namespace: "{{SITE_NAMESPACE}}"
    definition: "{{ lookup('template', '{{ SITE_SRC }}/openshift/SITE_SECRET_1.yml') }}"
    validate_certs: false
- name: Install {{ SITE_NAME }} build config 1 on OpenShift
  k8s:
    state: present
    name: "{{ SITE_NAME }}"
    host: "{{SITE_HOST}}"
    api_key: "{{SITE_TOKEN}}"
    namespace: "{{SITE_NAMESPACE}}"
    definition: "{{ lookup('template', '{{ SITE_SRC }}/openshift/SITE_BUILD_CONFIG_1.yml') }}"
    validate_certs: false
  when: SITE_BUILD_CONFIG_1
- name: Install {{ SITE_NAME }} deployment config on OpenShift
  k8s:
    state: present
    name: "{{ SITE_NAME }}"
    host: "{{SITE_HOST}}"
    api_key: "{{SITE_TOKEN}}"
    namespace: "{{SITE_NAMESPACE}}"
    definition: "{{ lookup('template', '{{ SITE_SRC }}/openshift/SITE_DEPLOYMENT_CONFIG_1.yml') }}"
    validate_certs: false
- name: Install {{ SITE_NAME }} service on OpenShift
  k8s:
    state: present
    name: "{{ SITE_NAME }}"
    host: "{{SITE_HOST}}"
    api_key: "{{SITE_TOKEN}}"
    namespace: "{{SITE_NAMESPACE}}"
    definition: "{{ lookup('template', '{{ SITE_SRC }}/openshift/SITE_SERVICE_1.yml') }}"
    validate_certs: false
- name: Install {{ SITE_NAME }} route on OpenShift
  k8s:
    state: present
    name: "{{ SITE_NAME }}"
    host: "{{SITE_HOST}}"
    api_key: "{{SITE_TOKEN}}"
    namespace: "{{SITE_NAMESPACE}}"
    definition: "{{ lookup('template', '{{ SITE_SRC }}/openshift/SITE_ROUTE_1.yml') }}"
    validate_certs: false
  ignore_errors: true
- name: Create Solr collection
  shell: "oc login {{ SOLR_HOST }} --token={{ REDHAT_OPENSHIFT_TOKEN }} && oc exec $(oc get pod -l app=solr -o jsonpath='{.items[0].metadata.name}' -n {{ SOLR_NAMESPACE }}) -n {{ SOLR_NAMESPACE }} -- /opt/solr/bin/solr create_collection -c {{ SOLR_COLLECTION }} -n computate || true"
  register: create_collection
- name: Print create_collection command
  debug:
    var: create_collection
